/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import com.mycompany.models.PrendaDeVestir;
import com.mycompany.service.GestorDatos;
import com.mycompany.service.GenPrendas;
import com.mycompany.IO.lectorTXT;
import com.mycompany.sorting.AlgoritmoOrdenamiento;
import com.mycompany.sorting.BubbleSort;
import com.mycompany.sorting.SelectionSort;
import com.mycompany.sorting.InsertionSort;
import com.mycompany.sorting.MergeSort;
import com.mycompany.sorting.QuickSort;
import com.mycompany.sorting.HeapSort;

import com.mycompany.STATS.ResultadoOrdenamiento;
import com.mycompany.service.GestorResultados;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class NewJPanel extends javax.swing.JPanel {

    private GestorDatos gestor = new GestorDatos();
    private GenPrendas generador = new GenPrendas();
    private lectorTXT lector = new lectorTXT();
    private GestorResultados gestorResultados = new GestorResultados();
    /**private GenPrendas generador = new GenPrendas();
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void mostrarPrendasEnTabla(List<PrendaDeVestir> prendas) {

    DefaultTableModel modelo = (DefaultTableModel) tblPrendas.getModel();

    modelo.setRowCount(0);

    for (PrendaDeVestir prenda : prendas) {

        modelo.addRow(new Object[]{
            prenda.getCodigo(),
            prenda.getNombre(),
            prenda.getCategoria(),
            prenda.getTalla(),
            prenda.getMarca(),
            prenda.getCantidadDisponible(),
            prenda.getPrecio()
        });

    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAlgoritmos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrendas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlgoritmo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        btnComparar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SpinerCantidad = new javax.swing.JSpinner();
        lblCantidad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        btnCargarTXT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        cmbAlgoritmos.setBackground(new java.awt.Color(0, 102, 153));
        cmbAlgoritmos.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        cmbAlgoritmos.setForeground(new java.awt.Color(255, 255, 255));
        cmbAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUBBLE SORT", "QUICK SORT", "MERGE SORT", "HEAP SORT", "INSERTION SORT", "SELECTION SORT" }));
        cmbAlgoritmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlgoritmosActionPerformed(evt);
            }
        });

        tblPrendas.setBackground(new java.awt.Color(102, 102, 255));
        tblPrendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "CATEGORIA", "TALLA", "MARCA", "CANTIDAD", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tblPrendas);

        tblAlgoritmo.setBackground(new java.awt.Color(102, 102, 255));
        tblAlgoritmo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ALGORITMO", "COMPARACIONES", "INTERCAMBIOS", "TIEMPO (ms)"
            }
        ));
        jScrollPane2.setViewportView(tblAlgoritmo);

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALGORITMO");

        lblEstado.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lblEstado.setText("Estado: Esperando datos");

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("PRENDAS CARGADAS");

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel4.setText("RESULTADOS DE LOS ALGORITMOS");

        btnOrdenar.setBackground(new java.awt.Color(0, 153, 153));
        btnOrdenar.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnComparar.setBackground(new java.awt.Color(0, 102, 153));
        btnComparar.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnComparar.setForeground(new java.awt.Color(255, 255, 255));
        btnComparar.setText("COMPARAR");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        SpinerCantidad.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        SpinerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblCantidad.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        lblCantidad.setText("CANTIDAD");

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel5.setText("DATOS");

        btnGenerar.setBackground(new java.awt.Color(0, 102, 153));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("GENERAR ALEATORIO");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnCargarTXT.setBackground(new java.awt.Color(0, 102, 153));
        btnCargarTXT.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarTXT.setText("CARGAR TXT");
        btnCargarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SpinerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGenerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(btnCargarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCantidad))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCargarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(444, 444, 444)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComparar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addComponent(btnOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAlgoritmos))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnComparar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clothes Sort");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTXTActionPerformed
        // TODO add your handling code here:
           JFileChooser selector = new JFileChooser();

        int opcion = selector.showOpenDialog(this);

            if (opcion == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            lector.cargarArchivo(archivo, gestor);

            mostrarPrendasEnTabla(gestor.obtenerPrendas());

            lblEstado.setText("Estado: Archivo cargado correctamente.");

            }

    }//GEN-LAST:event_btnCargarTXTActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        String opcion = cmbAlgoritmos.getSelectedItem().toString();
        lblEstado.setText("Estado: Algoritmo ejecutado -> " + opcion);

        AlgoritmoOrdenamiento algoritmo = null;

        switch (opcion) {

            case "BUBBLE SORT":
                algoritmo = new BubbleSort();
                break;

            case "SELECTION SORT":
                algoritmo = new SelectionSort();
                break;

            case "INSERTION SORT":
                algoritmo = new InsertionSort();
                break;

            case "MERGE SORT":
                algoritmo = new MergeSort();
                break;

            case "QUICK SORT":
                algoritmo = new QuickSort();
                break;

            case "HEAP SORT":
                algoritmo = new HeapSort();
                break;
        }
        if (algoritmo == null) {
        System.out.println("No se seleccionó un algoritmo válido.");
        } else {
            System.out.println("Algoritmo seleccionado: " + opcion);
        }
        
        if (gestorResultados.existeAlgoritmo(opcion)) {

            JOptionPane.showMessageDialog(
                this,
                "El algoritmo " + opcion + " ya fue ejecutado.",
                "Aviso",
                JOptionPane.INFORMATION_MESSAGE
            );

            return;
        }
        ResultadoOrdenamiento resultado = algoritmo.ordenar(gestor.obtenerPrendas());
        gestorResultados.agregarResultado(resultado);
        if (gestorResultados.obtenerResultados().size() == 6) {

            btnOrdenar.setEnabled(false);

            lblEstado.setText("Estado: Todos los algoritmos fueron ejecutados.");

        }
        
        
        mostrarPrendasEnTabla(resultado.getPrendasOrdenadas());
        
        DefaultTableModel modelo = (DefaultTableModel) tblAlgoritmo.getModel();

        System.out.println(resultado.getTiempoEjecucion());
        modelo.insertRow(0, new Object[]{
            resultado.getNombreAlgoritmo(),
            resultado.getComparaciones(),
            resultado.getIntercambios(),
            String.format("%.3f", resultado.getTiempoEjecucion())
        });

        lblEstado.setText("Estado: " + resultado.getNombreAlgoritmo() + " ejecutado correctamente.");
        
        

        System.out.println("----- LISTA ORDENADA -----");

        for (PrendaDeVestir p : resultado.getPrendasOrdenadas()) {
            System.out.println(p.getPrecio());
        }
       
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        // TODO add your handling code here:
        List<ResultadoOrdenamiento> resultados = gestorResultados.obtenerResultados();

        if (resultados.size() < 2) {
            JOptionPane.showMessageDialog(
                this,
                "Debe ejecutar al menos dos algoritmos para comparar.",
                "Comparación",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        ResultadoOrdenamiento mejorTiempo = resultados.get(0);
        ResultadoOrdenamiento mejorComparaciones = resultados.get(0);
        ResultadoOrdenamiento mejorIntercambios = resultados.get(0);
        ResultadoOrdenamiento peorTiempo = resultados.get(0);
        ResultadoOrdenamiento peorComparaciones = resultados.get(0);
        ResultadoOrdenamiento peorIntercambios = resultados.get(0);

        for (ResultadoOrdenamiento r : resultados) {

            if (r.getTiempoEjecucion() < mejorTiempo.getTiempoEjecucion()) {
                mejorTiempo = r;
            }

            if (r.getComparaciones() < mejorComparaciones.getComparaciones()) {
                mejorComparaciones = r;
            }

            if (r.getIntercambios() < mejorIntercambios.getIntercambios()) {
                mejorIntercambios = r;
            }
            
            if (r.getTiempoEjecucion() > peorTiempo.getTiempoEjecucion()) {
                peorTiempo = r;
            }

            if (r.getComparaciones() > peorComparaciones.getComparaciones()) {
                peorComparaciones = r;
            }

            if (r.getIntercambios() > peorIntercambios.getIntercambios()) {
                peorIntercambios = r;
            }
        }
        FrmComparacion ventana = new FrmComparacion(
                mejorTiempo,
                peorTiempo,
                mejorComparaciones,
                peorComparaciones,
                mejorIntercambios,
                peorIntercambios
        );

        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) SpinerCantidad.getValue();
        
        if (cantidad <= 0) {
        JOptionPane.showMessageDialog(
            this,
            "Debe ingresar una cantidad mayor que cero.",
            "Cantidad inválida",
            JOptionPane.WARNING_MESSAGE
        );
        return;
        }

        gestor.limpiarLista();

        generador.generarPrendas(cantidad, gestor);

        mostrarPrendasEnTabla(gestor.obtenerPrendas());

        lblEstado.setText("Se generaron " + cantidad + " prendas.");
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void cmbAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbAlgoritmosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        // Limpiar la lista del backend
            gestor.limpiarLista();
            
            gestorResultados.limpiarResultados();
            
            btnOrdenar.setEnabled(true);
            

            // Limpiar la tabla
            DefaultTableModel modelo = (DefaultTableModel) tblPrendas.getModel();
            modelo.setRowCount(0);
            
            DefaultTableModel modeloAlgoritmo = (DefaultTableModel) tblAlgoritmo.getModel();
            modeloAlgoritmo.setRowCount(0);

            // Reiniciar el ComboBox
            cmbAlgoritmos.setSelectedIndex(0);

            // Reiniciar el Spinner (si tienes uno)
            SpinerCantidad.setValue(1);

            // Actualizar el estado
            lblEstado.setText("Estado: Sistema limpio.");
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinerCantidad;
    private javax.swing.JButton btnCargarTXT;
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTable tblAlgoritmo;
    private javax.swing.JTable tblPrendas;
    // End of variables declaration//GEN-END:variables
}
